graph TD
    A[Start] --> B[index rooms in the map object by their IDs ];
    B --> C[init array alreadyVisitedRoomIDs]
    C --> G[init array result]
    G --> R[init FIFO queue roomsToVisit, add start room ID to roomsToVisit]
    R --> D[set currentRoom = head of roomsToVisit ]
    D --> E[add currentRoom's ID to alreadyVisitedRoomIDs]    
    E --> F[Collect target objects from the current room and add element to the result array]
    F --> I{currentRoom has connectedRooms?}
    I -->|Yes| J[Search for connected rooms ID that do not compare in alreadyVisitedRoomIDs and add them to roomsToVisit]
    J --> E
    I -->|No| K{roomsToVisit is empty?}
    K -->|Yes| Q[Print Result]
    K -->|No| D
    Q --> Z[End]

